# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compile an original libSBGN Schematron schema.
#'
#' @param schema_path Path to the authoritative schema.
#' @param phase Schematron phase to activate.
#' @param namespace_policy Namespace policy identifier.
#' @param effective_sbgn_namespace Effective namespace for the `sbgn` prefix.
#' @return An external pointer to a compiled schema.
schematron_compile_cpp <- function(schema_path, phase, namespace_policy, effective_sbgn_namespace) {
    .Call(`_sbgnvalidator_schematron_compile_cpp`, schema_path, phase, namespace_policy, effective_sbgn_namespace)
}

#' Validate an SBGN-ML document with a compiled schema.
#'
#' @param schema_pointer External pointer returned by `schematron_compile_cpp`.
#' @param document_path Path to the SBGN-ML document.
#' @return A normalized validation report.
schematron_validate_cpp <- function(schema_pointer, document_path) {
    .Call(`_sbgnvalidator_schematron_validate_cpp`, schema_pointer, document_path)
}

#' Inspect the root namespace and language of the first SBGN map.
#'
#' @param document_path Path to the SBGN-ML document.
#' @return The root namespace and SBGN map language.
sbgn_document_info_cpp <- function(document_path) {
    .Call(`_sbgnvalidator_sbgn_document_info_cpp`, document_path)
}

