// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// schematron_compile_cpp
SEXP schematron_compile_cpp(const std::string& schema_path, const std::string& phase, const std::string& namespace_policy, const std::string& effective_sbgn_namespace);
RcppExport SEXP _sbgnvalidator_schematron_compile_cpp(SEXP schema_pathSEXP, SEXP phaseSEXP, SEXP namespace_policySEXP, SEXP effective_sbgn_namespaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type schema_path(schema_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type phase(phaseSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type namespace_policy(namespace_policySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type effective_sbgn_namespace(effective_sbgn_namespaceSEXP);
    rcpp_result_gen = Rcpp::wrap(schematron_compile_cpp(schema_path, phase, namespace_policy, effective_sbgn_namespace));
    return rcpp_result_gen;
END_RCPP
}
// schematron_validate_cpp
Rcpp::List schematron_validate_cpp(SEXP schema_pointer, const std::string& document_path);
RcppExport SEXP _sbgnvalidator_schematron_validate_cpp(SEXP schema_pointerSEXP, SEXP document_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type schema_pointer(schema_pointerSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type document_path(document_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(schematron_validate_cpp(schema_pointer, document_path));
    return rcpp_result_gen;
END_RCPP
}
// sbgn_document_info_cpp
Rcpp::List sbgn_document_info_cpp(const std::string& document_path);
RcppExport SEXP _sbgnvalidator_sbgn_document_info_cpp(SEXP document_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type document_path(document_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(sbgn_document_info_cpp(document_path));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sbgnvalidator_schematron_compile_cpp", (DL_FUNC) &_sbgnvalidator_schematron_compile_cpp, 4},
    {"_sbgnvalidator_schematron_validate_cpp", (DL_FUNC) &_sbgnvalidator_schematron_validate_cpp, 2},
    {"_sbgnvalidator_sbgn_document_info_cpp", (DL_FUNC) &_sbgnvalidator_sbgn_document_info_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_sbgnvalidator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
