"""Generate the runtime matrix from executable oracle comparison results."""

import argparse
import json
from pathlib import Path

from compare_results import semantic_finding

RUNTIMES = {
    "java": {
        "engine": "ph-schematron-schxslt2 10.0.1 + SchXslt2 1.11.2 + Saxon-HE 12.10",
        "strategy": "reference Schematron-to-XSLT pipeline",
    },
    "javascript": {
        "engine": "node-schematron 2.1.0 + FontoXPath 3.34.0",
        "strategy": "native direct interpreter with profile adapter",
    },
    "r": {
        "engine": "project Rcpp interpreter + system libxml2",
        "strategy": "native direct profile interpreter",
    },
    "rust": {
        "engine": "vendored schematron 0.5.1 profile patch",
        "strategy": "native direct interpreter",
    },
    "go": {
        "engine": "Helium 0.8.0 XPath 3.1",
        "strategy": "native direct profile interpreter",
    },
    "python": {
        "engine": "pyschematron 1.2.1 + elementpath 5.0.4",
        "strategy": "native direct interpreter with profile adapter",
    },
}


def reports_match(oracle_root: Path, runtime_root: Path) -> bool:
    """Return whether all runtime reports semantically match Java.

    Args:
        oracle_root: Directory containing verified Java reports.
        runtime_root: Directory containing one runtime's reports.

    Returns:
        True when every oracle report has an equivalent runtime report.
    """
    for oracle_path in sorted(oracle_root.rglob("*.json")):
        actual_path = runtime_root / oracle_path.relative_to(oracle_root)
        if not actual_path.exists():
            return False
        expected = json.loads(oracle_path.read_text())
        actual = json.loads(actual_path.read_text())
        expected_findings = [semantic_finding(item) for item in expected["findings"]]
        actual_findings = [semantic_finding(item) for item in actual["findings"]]
        metadata_matches = all(
            expected.get(field) == actual.get(field) for field in ("schema", "phase", "valid")
        )
        if not metadata_matches or expected_findings != actual_findings:
            return False
    return True


def write_markdown(
    path: Path, statuses: dict[str, bool], fixture_count: int, version: str
) -> None:
    """Write the human-readable runtime and capability matrix.

    Args:
        path: Markdown destination.
        statuses: Executable equivalence result by runtime.
        fixture_count: Number of oracle cases compared.
    """
    lines = [
        "# Runtime and capability matrix",
        "",
        "This file is generated by `tools/generate_capability_matrix.py`. A `PASS`",
        "means that the backend compiled the original three schemas and matched all",
        f"{fixture_count} normalized Java oracle reports. It is not a documentation-only claim.",
        "",
        "| Runtime | Version | Engine | Strategy | Corpus equivalence |",
        "|---|---|---|---|---|",
    ]
    for runtime, metadata in RUNTIMES.items():
        status = "PASS" if statuses[runtime] else "FAIL"
        lines.append(
            f"| {runtime} | {version} | {metadata['engine']} | "
            f"{metadata['strategy']} | {status} |"
        )
    lines.extend(
        [
            "",
            "The executable profile covers phases, namespaces, rule variables, assertions,",
            "diagnostics and `value-of`, nested predicate `current()`, `distinct-values()`,",
            "`position()`, `local-name()`, `namespace-uri()`, and normalized `current-time()`.",
            "Unsupported constructs outside the inventoried profile fail closed.",
            "",
        ]
    )
    path.write_text("\n".join(lines))


def main() -> None:
    """Generate JSON and Markdown capability evidence."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--benchmark-root", type=Path, default=Path("."))
    args = parser.parse_args()
    root = args.benchmark_root.resolve()
    oracle_root = root / "conformance" / "oracle" / "java"
    fixture_count = len(list(oracle_root.rglob("*.json")))
    statuses = {"java": fixture_count > 0}
    for runtime in RUNTIMES:
        if runtime == "java":
            continue
        statuses[runtime] = reports_match(oracle_root, root / "build" / "results" / runtime)

    xpath = json.loads(
        (root / "conformance" / "profile" / "xpath-features.json").read_text()
    )
    schematron = json.loads(
        (root / "conformance" / "profile" / "schematron-features.json").read_text()
    )
    payload = {
        "profile": xpath["profile"],
        "evidence": f"{fixture_count} normalized reports compared with Java",
        "runtimes": statuses,
        "schematron_constructs": {
            feature: statuses for feature in sorted(schematron["constructs"])
        },
        "xpath_functions": {feature: statuses for feature in sorted(xpath["functions"])},
    }
    output = root / "conformance" / "profile" / "capability-matrix.json"
    output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    version = (root / "VERSION").read_text().strip()
    write_markdown(
        root / "docs" / "runtime-matrix.md", statuses, fixture_count, version
    )
    if not all(statuses.values()):
        failed = ", ".join(runtime for runtime, passed in statuses.items() if not passed)
        raise SystemExit(f"corpus equivalence failed: {failed}")
    print(f"all {len(statuses)} runtimes match {fixture_count} Java reports")


if __name__ == "__main__":
    main()
